# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 13:13
from __future__ import unicode_literals

from django.db import migrations


def set_email_verification(apps, schema_editor):
    User = apps.get_model("auth", "user")
    EmailVerification = apps.get_model("resturo", "EmailVerification")

    for u in User.objects.all():
        ev, created = EmailVerification.objects.get_or_create(user=u)
        if created:
            ev.verified = True
            ev.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resturo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_email_verification),
    ]
